apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-v2
  labels:
    app: titanic
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic
      version: v2
  template:
    metadata:
      labels:
        app: titanic # What is template?
        version: v2
    spec:
      containers:
        - name: titanic
          image: "eu.gcr.io/xccel-266717/titanic:v2"
          args: []
          ports:
              - containerPort: 5000
          volumeMounts:
            - mountPath: /model
              name: model
      initContainers:
        - name: titanic-download-model
          image: "eu.gcr.io/xccel-266717/titanic:v1"
          command: ["titanic", "download-data",
                    "--gcp-path",
                    "gs://titanic-xcc-model-deployment/model/model.pkl" ,
                    "--output-path", "/model/model.pkl", "--auth-key-path",
                    "/secret/read"
                    ] # command is going to override everything, entrypoint + cmd, else just args? (that takes entrypoint from Dockerfile)
          volumeMounts:
            - mountPath: /secret
              name: gcp-secret-getter
            - mountPath: /model
              name: model
      volumes:
      - name: gcp-secret-getter
        secret:
            secretName: storage-key
      - name: model
        emptyDir: {}
